import uuid
from datetime import datetime
from typing import List

from pydantic import BaseModel, Field


class TextSafeArea(BaseModel):
    """A rectangular region of the thumbnail frame reserved for overlay text,
    expressed as fractions of frame width/height (0.0-1.0) so it stays
    resolution-independent for a future rendering stage - no pixels are
    committed to here."""

    label: str  # e.g. "title", "lower_third"
    x: float
    y: float
    width: float
    height: float


class ThumbnailVariant(BaseModel):
    """One candidate thumbnail's full strategy. The plan carries a *list* of
    these (responsibility 7: support future multiple variants) even though
    this milestone emits exactly one - a later A/B stage can append more
    without any schema change. image_prompt is composed deterministically
    from the Character Bible's paste-ready reference_prompt and the story
    fields; it is not generated by an LLM."""

    variant_id: str
    strategy: str
    focal_subject: str
    emotion: str
    composition: str
    image_prompt: str
    source_scene_id: int
    source_shot_id: int
    text_safe_areas: List[TextSafeArea] = Field(default_factory=list)


class ThumbnailPlan(BaseModel):
    """Public output contract (ARCHITECTURE.md SS6/SS12) - Producer Package's
    thumbnail_plan.json. A strategy/prompt blueprint only: no thumbnail image
    is generated, edited, or published here - those are later, still-
    unimplemented stages' jobs."""

    thumbnail_plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    source_editing_plan_id: str = ""
    variants: List[ThumbnailVariant] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=datetime.utcnow)
