"""
Integration proof for Milestone V2 requirement 7 (Execution Engine
compatibility): a clip the Video Generation Engine's StubProvider produced is
consumed by the entirely unchanged FFmpeg Execution Engine exactly like any
other video asset - confirming the hybrid image/video rendering model
ARCHITECTURE.md SS25.2 documents still holds once a real generated clip (not
just a human-imported one) sits in media/video/. No file in execution_engine/
is touched by this milestone; this test is the evidence for that claim.

Skipped when ffmpeg isn't available, following the same convention as
tests/integration/test_filter_graph_builder_real_ffmpeg.py.
"""

import subprocess

import pytest

from execution_engine.command_builder import build_command, validate_render_request
from execution_engine.ffmpeg_detector import detect_ffmpeg
from execution_engine.ffmpeg_executor import execute
from execution_engine.ffprobe_client import probe as execution_probe
from execution_engine.postflight import validate_render
from execution_engine.preflight import verify_media_exists
from shared_core.contracts.asset_manifest import ValidatedAssetManifest
from shared_core.contracts.editing_plan import EditingPlan, EditingSegment
from shared_core.contracts.music_plan import MusicPlan
from shared_core.contracts.prompt_set import ShotPrompt
from shared_core.contracts.render import RenderOptions, RenderRequest
from shared_core.contracts.subtitle import SubtitlePlan
from shared_core.contracts.timeline import Timeline
from shared_core.contracts.video_generation import VideoGenerationOptions, VideoGenerationRequest
from video_generation_engine.providers.stub import StubProvider

_ffmpeg_info = detect_ffmpeg()
pytestmark = pytest.mark.skipif(not _ffmpeg_info.available, reason="ffmpeg not available on this machine")


def _make_tiny_image(path, size="640x360"):
    subprocess.run(
        [_ffmpeg_info.path, "-y", "-f", "lavfi", "-i", f"color=c=blue:s={size}:d=1",
         "-frames:v", "1", str(path), "-loglevel", "error"],
        check=True, timeout=30,
    )


def _make_tiny_audio(path, duration=4.0):
    subprocess.run(
        [_ffmpeg_info.path, "-y", "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
         "-t", str(duration), str(path), "-loglevel", "error"],
        check=True, timeout=30,
    )


def test_stub_generated_clip_renders_alongside_an_image_through_the_real_pipeline(tmp_path):
    # ---- Shot 1 stays an image (today's default, unchanged); shot 2 is generated by the Video Generation Engine ----
    image_path = tmp_path / "scene_1_shot_1.png"
    _make_tiny_image(image_path)

    video_dir = tmp_path / "media" / "video"
    video_dir.mkdir(parents=True)
    shot_prompt = ShotPrompt(
        scene_id=1, shot_id=2, duration_seconds=2, image_prompt="x" * 50,
        video_motion_prompt="camera slowly zooms in on the subject",
    )
    generation_request = VideoGenerationRequest(
        shot_prompt=shot_prompt, scene_id=1, shot_id=2, output_dir=str(video_dir),
        options=VideoGenerationOptions(provider="stub", resolution="640x360", aspect_ratio="16:9", fps=24),
    )
    generation_result = StubProvider().generate(generation_request)
    assert generation_result.success is True, generation_result.error
    video_path = video_dir / "scene_1_shot_2.mp4"
    assert video_path.is_file()

    narration_path = tmp_path / "voice_script.wav"
    _make_tiny_audio(narration_path, duration=4.0)

    # ---- A RenderRequest whose segments mix "image" and "video" asset_type - the exact hybrid model SS25.2 documents ----
    manifest = ValidatedAssetManifest(
        manifest_id="m1", source_prompt_set_id="ps", is_valid=True, narration_audio_path=str(narration_path),
    )
    timeline = Timeline(timeline_id="tl1", source_asset_manifest_id="m1")
    subtitle_plan = SubtitlePlan(subtitle_plan_id="sp1", source_timeline_id="tl1")
    music_plan = MusicPlan(music_plan_id="mp1", source_timeline_id="tl1")
    editing_plan = EditingPlan(
        editing_plan_id="ep1", source_timeline_id="tl1", source_subtitle_plan_id="sp1", source_music_plan_id="mp1",
        segments=[
            EditingSegment(
                scene_id=1, shot_id=1, asset_path=str(image_path), asset_type="image",
                start_time=0.0, end_time=2.0, music_cue_scene_id=1, transition_in="cut", transition_out="cut",
            ),
            EditingSegment(
                scene_id=1, shot_id=2, asset_path=str(video_path), asset_type="video",
                start_time=2.0, end_time=4.0, music_cue_scene_id=1, transition_in="cut", transition_out="cut",
            ),
        ],
        total_duration_seconds=4.0,
    )
    request = RenderRequest(
        editing_plan=editing_plan, asset_manifest=manifest, timeline=timeline,
        subtitle_plan=subtitle_plan, music_plan=music_plan, output_dir=str(tmp_path / "renders"),
        options=RenderOptions(resolution="640x360", fps=24, timeout_seconds=60),
    )

    # ---- The Execution Engine runs entirely unmodified ----
    validate_render_request(request)
    verify_media_exists(request)
    command_spec = build_command(request)

    render_result = execute(command_spec, ffmpeg_path=_ffmpeg_info.path, timeout_seconds=60)
    assert render_result.success is True, render_result.error

    probed = execution_probe(render_result.output_path, ffprobe_path="ffprobe")
    validation_report = validate_render(probed, editing_plan, request.options, output_path=render_result.output_path)
    assert validation_report.is_valid is True, [c for c in validation_report.checks if not c.passed]
